server:
    port: 8988

data-source:
    host: http://hasura.infect.joinbox.com/v1/graphql
    secret: ${hasura_secret}


models:
    # tenant:
    #     tenant:
    #         _properties:
    #             - id
    #             - identifier
    #             - name
    #     domain:
    #         _properties:
    #             - id
    #             - id_tenant
    #             - name
    #     featureFlag:
    #         _properties:
    #             - id
    #             - identifier
    #     tenant_featureFlag:
    #         _properties:
    #             - id
    #             - id_tenant
    #             - id_featureFlag
    #             - enabled
    #     configuration:
    #         _properties:
    #             - id
    #             - identifier
    #     tenant_configuration:
    #             - id
    #             - id_tenant
    #             - id_configuration
    #             - data


    guideline:
        diagnosis:
            _properties:
                - id
                - id_diagnosisClass
                - id_guideline
                - identifier
                - name
                - markdownText
                - href
                - synonyms
                - hidden

            _hiddenFilter: 
                guideline: 
                    hidden:
                        _eq: false
                hidden:
                    _eq: false

            _tenantFilter:

                guideline:
                    guideline_tenants:
                        tenant:
                            id:  
                                _eq: $(tenantId)
            
            therapies:
                therapyDataUpdates:
                    _properties:
                        - date
                    _limit: 1
                    _order_by:
                        date: desc 

                    dataSource:
                        _properties:
                            - name
                            - href

            _forEach: >
                class ForEach {
                    execute(record) {
                        const latestUpdates = [];

                        if (record.therapies) {
                            record.therapies.forEach((therapy) => {
                                if (therapy.therapyDataUpdates) {
                                    therapy.therapyDataUpdates.forEach((update) => {
                                        latestUpdates.push({
                                            date: update.date,
                                            dataSourceName: update.dataSource.name,
                                            dataSourceHref: update.dataSource.href,
                                        });
                                    });
                                }
                            });
                        }

                        if (record.synonyms) {
                            record.synonyms = record.synonyms.split(/\s*,\s*/gi);
                            } else {
                                record.synonyms = [];
                            }

                        record.latestUpdates = latestUpdates;
                        delete record.therapies;
                    };
                }
                ForEach



        diagnosis_bacterium:
            _properties:
                - id
                - id_bacterium
                - id_diagnosis
            _hiddenFilter: 
                diagnosis:
                    guideline:
                        hidden:
                            _eq: false
                    hidden:
                        _eq: false
            _tenantFilter:
                diagnosis:
                    guideline:
                        guideline_tenants:
                            tenant:
                                id:  
                                    _eq: $(tenantId)
        # dataSource:
        #     _properties:
        #         - id
        #         - href
        #         - name
        diagnosisClass:
            _properties:
                - id
                - name
                - identifier
        guideline:
            _properties:
                - id
                - name
                - markdownDisclaimer
                - hidden
                - contactEmail
            _hiddenFilter:
                hidden:
                    _eq: false
            _tenantFilter:
                guideline_tenants:
                    tenant:
                        id:  
                            _eq: $(tenantId)
        therapy:
            _properties:
                - id
                - id_diagnosis
                - id_therapyPriority
                - markdownText
            _hiddenFilter: 
                diagnosis:
                    guideline:
                        hidden:
                            _eq: false
            _tenantFilter:
                diagnosis:
                    guideline:
                        guideline_tenants:
                            tenant:
                                id: 
                                    _eq: $(tenantId)
        therapy_compound:
            _properties:
                - id
                - id_compound
                - id_therapy
                - markdownText
            _hiddenFilter:
                therapy:
                    diagnosis:
                        guideline:
                            hidden:
                                _eq: false
            _tenantFilter:
                therapy:
                    diagnosis:
                        guideline:
                            guideline_tenants:
                                tenant:
                                    id: 
                                        _eq: $(tenantId)
        # therapyDataUpdate:
        #     _properties:
        #         - id
        #         - id_dataSource
        #         - id_therapy
        #         - date
        #         - comment
        #     _hiddenFilter:
        #         therapy:
        #             diagnosis:
        #                 guideline:
        #                     hidden:
        #                         _eq: false
        #     _tenantFilter:
        #         therapy:
        #             diagnosis:
        #                 guideline:
        #                     guideline_tenants:
        #                         tenant:
        #                             id: 
        #                                 _eq: $(tenantId)
        therapyPriority:
            _properties:
                - id
                - priority
                - name