server:
    port: 8988

data-source:
    host: http://hasura.infect.joinbox.com/v1/graphql
    secret: ${hasura_secret}


models:
    tenant:
        tenant:
            properties:
                - id
                - identifier
                - name
        domain:
            properties:
                - id
                - id_tenant
                - name
        featureFlag:
            properties:
                - id
                - identifier
        tenant_featureFlag:
            properties:
                - id
                - id_tenant
                - id_featureFlag
                - enabled
        configuration:
            properties:
                - id
                - identifier
        tenant_configuration:
                - id
                - id_tenant
                - id_configuration
                - data


    guideline:
        diagnosis:
            properties:
                - id
                - id_diagnosisClass
                - id_guideline
                - identifier
                - name
                - markdownText
                - href
                - synonyms
                - hidden
            mapper: () => {}
            hiddenFilter: 
                guideline: 
                    hidden:
                        _eq: false
                hidden:
                    _eq: false
        diagnosis_bacterium:
            properties:
                - id
                - id_bacterium
                - id_diagnosis
            hiddenFilter: 
                diagnosis:
                    guideline:
                        hidden:
                            _eq: false
                    hidden:
                        _eq: false
        dataSource:
            properties:
                - id
                - href
                - name
        diagnosisClass:
            properties:
                - id
                - name
                - identifier
        guideline:
            properties:
                - id
                - name
                - markdownDisclaimer
                - hidden
                - contactEmail
            filter:
                _eq: false
        therapy:
            properties:
                - id
                - id_diagnosis
                - id_therapyPriority
                - markdownText
            hiddenFilter: 
                diagnosis:
                    guideline:
                        hidden:
                            _eq: false
        therapy_compound:
            properties:
                - id
                - id_compound
                - id_therapy
                - markdownText
            hiddenFilter:
                therapy:
                    diagnosis:
                        guideline:
                            hidden:
                                _eq: false
        therapyDataUpdate:
            properties:
                - id
                - id_dataSource
                - id_therapy
                - date
                - comment
            hiddenFilter:
                therapy:
                    diagnosis:
                        guideline:
                            hidden:
                                _eq: false
        therapyPriority:
            properties:
                - id
                - priority
                - name